package com.coderulez.senai.leansurvey.model;


/**
 * Condition generated by hbm2java
 */

public class Condition{

	private Long id;
	private String description;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
