package com.coderulez.senai.leansurvey.model;
import android.os.Parcel;
import android.os.Parcelable;

/**
 * Enterprise generated by hbm2java
 */

public class Enterprise implements Parcelable
{

	private Long id;
	private String name;
	private String address;
	private String cnpj;
	private String logoPath;
	private String contactName;
	private String contactNumber;
	private String email;

	public Enterprise()
	{

	}

	protected Enterprise(Parcel in) {
		id = in.readLong();
		name = in.readString();
		address = in.readString();
		cnpj = in.readString();
		logoPath = in.readString();
		contactName = in.readString();
		contactNumber = in.readString();
		email = in.readString();
	}

	public static final Creator<Enterprise> CREATOR = new Creator<Enterprise>() {
		@Override
		public Enterprise createFromParcel(Parcel in) {
			return new Enterprise(in);
		}

		@Override
		public Enterprise[] newArray(int size) {
			return new Enterprise[size];
		}
	};

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public String getLogoPath() {
		return logoPath;
	}

	public void setLogoPath(String logoPath) {
		this.logoPath = logoPath;
	}

	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public int describeContents()
	{
		return 8;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags)
	{
		dest.writeLong(id);
		dest.writeString(name);
		dest.writeString(address);
		dest.writeString(cnpj);
		dest.writeString(logoPath);
		dest.writeString(contactName);
		dest.writeString(contactNumber);
		dest.writeString(email);
	}
}
