package com.coderulez.senai.leansurvey.model;


/**
 * Questionrule generated by hbm2java
 */

public class Questionrule {

	private Long id;
	private Condition condition;


	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Condition getCondition() {
		return condition;
	}

	public void setCondition(Condition condition) {
		this.condition = condition;
	}
}
