package com.coderulez.senai.leansurvey.model;



/**
 * Questiontype generated by hbm2java
 */

public class Questiontype implements java.io.Serializable {

	private Long id;
	private String description;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
