package com.coderulez.senai.leansurvey.model;

import java.util.Date;

/**
 * Questionnaireanswer generated by hbm2java
 */

public class Questionnaireanswer{

	private Long id;
	private Interviewer interviewer;
	private Questionnaire questionnaire;
	private Date date;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Interviewer getInterviewer() {
		return interviewer;
	}

	public void setInterviewer(Interviewer interviewer) {
		this.interviewer = interviewer;
	}

	public Questionnaire getQuestionnaire() {
		return questionnaire;
	}

	public void setQuestionnaire(Questionnaire questionnaire) {
		this.questionnaire = questionnaire;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
}
